/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        nord: {
          /* Tailwind-like Nord color names */
          0: "#2E3440",
          1: "#3B4252",
          2: "#434C5E",
          3: "#4C566A",
          4: "#D8DEE9",
          5: "#E5E9F0",
          6: "#ECEFF4",
          7: "#8FBCBB",
          8: "#88C0D0",
          9: "#81A1C1",
          10: "#5E81AC",
          11: "#BF616A",
          12: "#D08770",
          13: "#EBCB8B",
          14: "#A3BE8C",
          15: "#B48EAD",
        },
      },
      typography: ({ theme }) => ({
        nord: {
          css: {
            "--tw-prose-body": theme("colors.nord[0]"),
            "--tw-prose-headings": theme("colors.nord[0]"),
            "--tw-prose-lead": theme("colors.nord[7]"),
            "--tw-prose-links": theme("colors.nord[10]"),
            "--tw-prose-bold": theme("colors.nord[0]"),
            "--tw-prose-counters": theme("colors.nord[15]"),
            "--tw-prose-bullets": theme("colors.nord[8]"),
            "--tw-prose-hr": theme("colors.nord[3]"),
            "--tw-prose-quotes": theme("colors.nord[1]"),
            "--tw-prose-quote-borders": theme("colors.nord[8]"),
            "--tw-prose-captions": theme("colors.nord[0]"),
            "--tw-prose-code": theme("colors.nord[0]"),
            "--tw-prose-pre-code": theme("colors.nord[0]"),
            "--tw-prose-pre-bg": theme("colors.nord[5]"),
            "--tw-prose-th-borders": theme("colors.nord[4]"),
            "--tw-prose-td-borders": theme("colors.nord[4]"),

            "--tw-prose-invert-body": theme("colors.nord[6]"),
            "--tw-prose-invert-headings": theme("colors.nord[6]"),
            "--tw-prose-invert-lead": theme("colors.nord[7]"),
            "--tw-prose-invert-links": theme("colors.nord[8]"),
            "--tw-prose-invert-bold": theme("colors.nord[6]"),
            "--tw-prose-invert-counters": theme("colors.nord[8]"),
            "--tw-prose-invert-bullets": theme("colors.nord[8]"),
            "--tw-prose-invert-hr": theme("colors.nord[5]"),
            "--tw-prose-invert-quotes": theme("colors.nord[5]"),
            "--tw-prose-invert-quote-borders": theme("colors.nord[8]"),
            "--tw-prose-invert-captions": theme("colors.nord[6]"),
            "--tw-prose-invert-code": theme("colors.nord[6]"),
            "--tw-prose-invert-pre-code": theme("colors.nord[6]"),
            "--tw-prose-invert-pre-bg": theme("colors.nord[1]"),
            "--tw-prose-invert-th-borders": theme("colors.nord[3]"),
            "--tw-prose-invert-td-borders": theme("colors.nord[3]"),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
